### ISSUE TITLE
[Bug]: Failed to start dev server. Certificate not found at path "[...]\.aspnet\dev-certs\https\localhost.pfx"

### ISSUE THREAD

**Issue by thiagolunardi** [platformplatform/PlatformPlatform#649]
### Detailed description?

**Describe the bug**

I did a clean repository clone, installed the recommended tools via `winget`, and ran `dotnet run` under `application/account-management/AppHost`. Although all services are green in the Aspire dashboard, when I follow the `app-gateway` link, the app is not loaded in the browser. The browser console shows an error while fetching static Javascript files.

**Expected behavior**

Have all services and resources green in Aspire dashboard and able to open the gateway at `https://localhost:9000/`

**Additional context**

Browser's console:
![Image](https://github.com/user-attachments/assets/6574bc70-7dc4-4da5-9844-aa7ef2611fcf)

Here is the log from my `frontend-build`:
```
2024-12-28T12:23:00 back-office-webapp:dev: error   Failed to start dev server.
2024-12-28T12:23:00 account-management-webapp:dev: error   Failed to start dev server.
2024-12-28T12:23:00 account-management-webapp:dev: error   Certificate not found at path: C:\Users\ThiagoLunardi\.aspnet\dev-certs\https\localhost.pfx
2024-12-28T12:23:00 account-management-webapp:dev:     at C:\Projects\GitHub\platformplatform\PlatformPlatform\application\shared-webapp\build\dist\plugin\DevelopmentServerPlugin.js:40:27
2024-12-28T12:23:00 account-management-webapp:dev:     at Object.call (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:2401:36)
2024-12-28T12:23:00 account-management-webapp:dev:     at async modifyRsbuildConfig (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:5127:22)
2024-12-28T12:23:00 account-management-webapp:dev:     at async initRsbuildConfig (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:5204:9)
2024-12-28T12:23:00 account-management-webapp:dev:     at async Object.startDevServer (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:6347:26)
2024-12-28T12:23:00 account-management-webapp:dev:     at async Command.<anonymous> (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:6958:21)
2024-12-28T12:23:00 back-office-webapp:dev: error   Certificate not found at path: C:\Users\ThiagoLunardi\.aspnet\dev-certs\https\localhost.pfx
2024-12-28T12:23:00 back-office-webapp:dev:     at C:\Projects\GitHub\platformplatform\PlatformPlatform\application\shared-webapp\build\dist\plugin\DevelopmentServerPlugin.js:40:27
2024-12-28T12:23:00 back-office-webapp:dev:     at Object.call (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:2401:36)
2024-12-28T12:23:00 back-office-webapp:dev:     at async modifyRsbuildConfig (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:5127:22)
2024-12-28T12:23:00 back-office-webapp:dev:     at async initRsbuildConfig (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:5204:9)
2024-12-28T12:23:00 back-office-webapp:dev:     at async Object.startDevServer (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:6347:26)
2024-12-28T12:23:00 back-office-webapp:dev:     at async Command.<anonymous> (file:///C:/Projects/GitHub/platformplatform/PlatformPlatform/application/node_modules/@rsbuild/core/dist/index.js:6958:21)
2024-12-28T12:23:00 account-management-webapp:dev: npm error Lifecycle script `dev` failed with error:
2024-12-28T12:23:00 account-management-webapp:dev: npm error code 1
2024-12-28T12:23:00 account-management-webapp:dev: npm error path C:\Projects\GitHub\platformplatform\PlatformPlatform\application\account-management\WebApp
2024-12-28T12:23:00 account-management-webapp:dev: npm error workspace account-management-webapp@1.0.0
2024-12-28T12:23:00 account-management-webapp:dev: npm error location C:\Projects\GitHub\platformplatform\PlatformPlatform\application\account-management\WebApp
2024-12-28T12:23:00 account-management-webapp:dev: npm error command failed
2024-12-28T12:23:00 account-management-webapp:dev: npm error command C:\WINDOWS\system32\cmd.exe /d /s /c rsbuild dev
2024-12-28T12:23:00 back-office-webapp:dev: npm error Lifecycle script `dev` failed with error:
2024-12-28T12:23:00 back-office-webapp:dev: npm error code 1
2024-12-28T12:23:00 back-office-webapp:dev: npm error path C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp
2024-12-28T12:23:00 back-office-webapp:dev: npm error workspace back-office-webapp@1.0.0
2024-12-28T12:23:00 back-office-webapp:dev: npm error location C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp
2024-12-28T12:23:00 back-office-webapp:dev: npm error command failed
2024-12-28T12:23:00 back-office-webapp:dev: npm error command C:\WINDOWS\system32\cmd.exe /d /s /c rsbuild dev
2024-12-28T12:23:00
 account-management-webapp:dev: ERROR: command finished with error: command (C:\Projects\GitHub\platformplatform\PlatformPlatform\application\account-management\WebApp) C:\Program Files\nodejs\npm.cmd run dev exited (1)
2024-12-28T12:23:00
 back-office-webapp:dev: ERROR: command finished with error: command (C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp) C:\Program Files\nodejs\npm.cmd run dev exited (1)
2024-12-28T12:23:00
 account-management-webapp#dev: command (C:\Projects\GitHub\platformplatform\PlatformPlatform\application\account-management\WebApp) C:\Program Files\nodejs\npm.cmd run dev exited (1)
2024-12-28T12:23:00
 back-office-webapp#dev: command (C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp) C:\Program Files\nodejs\npm.cmd run dev exited (1)
2024-12-28T12:23:00 
2024-12-28T12:23:00  Tasks:    6 successful, 12 total
2024-12-28T12:23:00 Cached:    2 cached, 12 total
2024-12-28T12:23:00   Time:    19.955s 
2024-12-28T12:23:00 Failed:    account-management-webapp#dev, back-office-webapp#dev
2024-12-28T12:23:00 
2024-12-28T12:23:00
  ERROR  run failed: command  exited (1)
```

### Severity

Low

### Is this bug security related?

- [ ] This bug is related to security

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by thiagolunardi** [comment]
I manually generated the certificates by running the following:
```
dotnet dev-certs https --trust --export-path "$env:USERPROFILE\.aspnet\dev-certs\https\localhost.pfx" -p <your-password>
```

Now, I can launch the application via the gateway. However, I still see the following minor error under the `frontend-build` resource logs.

```
2024-12-28T12:58:34 back-office-webapp:dev: start   Building...
2024-12-28T12:58:36 back-office-webapp:dev: error   Compile error: 
2024-12-28T12:58:36 back-office-webapp:dev: Failed to compile, check the errors for troubleshooting.
2024-12-28T12:58:36 back-office-webapp:dev: File: C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp\shared\lib\router\router.tsx:1:1
2024-12-28T12:58:36 back-office-webapp:dev:   × Module not found: Can't resolve './routeTree.generated' in 'C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp\shared\lib\router'
2024-12-28T12:58:36 back-office-webapp:dev:    ╭─[2:26]
2024-12-28T12:58:36 back-office-webapp:dev:  1 │ import { createRouter } from "@tanstack/react-router";
2024-12-28T12:58:36 back-office-webapp:dev:  2 │ import { routeTree } from "./routeTree.generated";
2024-12-28T12:58:36 back-office-webapp:dev:    ·                           ───────────────────────
2024-12-28T12:58:36 back-office-webapp:dev:  3 │ // Set up a Router instance
2024-12-28T12:58:36 back-office-webapp:dev:  4 │ export const router = createRouter({
2024-12-28T12:58:36 back-office-webapp:dev:    ╰────
2024-12-28T12:58:36 back-office-webapp:dev: 
2024-12-28T12:58:36 back-office-webapp:dev:  @ ./bootstrap.tsx
2024-12-28T12:58:36 back-office-webapp:dev:  @ ./main.tsx
2024-12-28T12:58:36 back-office-webapp:dev: 
2024-12-28T12:58:36 back-office-webapp:dev: start   Building...
2024-12-28T12:58:36 back-office-webapp:dev: 
2024-12-28T12:58:36 back-office-webapp:dev: ♻️  Generating routes...
2024-12-28T12:58:37 back-office-webapp:dev: 🟡 Updating C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp\shared\lib\router\routeTree.generated.ts
2024-12-28T12:58:37 back-office-webapp:dev: ✅ Processed route in 143ms
```

**Comment by tjementum** [comment]
Hi Thiago,

Thanks for reporting this. This is the first time experiencing this, and it must work, so I will make sure to fix it.

When you start the `/Apphost` the first time, it should detect and generate a `localhost.pfx` with a known password that can be used by the frontend. [This is done here](https://github.com/platformplatform/PlatformPlatform/blob/90afd43ca5c997878550a4a7934cfb0ca35ad07f/application/AppHost/SslCertificateManager.cs#L41-L59).

Windows: C:\Users\<username>\.aspnet\dev-certs\https\localhost.pfx  
macOS: /Users/<username>/.aspnet/dev-certs/https/localhost.pfx  

Is this file not generated on your machine?

You could try to F5 debug in this method... it's literally [the 3rd line in program.cs](https://github.com/platformplatform/PlatformPlatform/blob/722d638420bfedc5a11c4fc72d69df77bf961457/application/AppHost/Program.cs#L12).

Also, are you running the latest version of PlatformPlatform? I had a bug when upgrading to .NET 9, but I don't recall the details. Maybe I did not fix it for WindowS?

**Comment by tjementum** [comment]
:) We posted at the same time. Great that you got it working, but this should work automatically.

As for the frontend error you get:


```Can't resolve './routeTree.generated'```

you can see that it is successfully generated this file in the second-to-last line:

```🟡 Updating C:\Projects\GitHub\platformplatform\PlatformPlatform\application\back-office\WebApp\shared\lib\router\routeTree.generated.ts```

So, you should be good. Do you have any problems running the system now?

PS: I don't have time today, but I would love to jump on a call and get any feedback from you if you like.

**Comment by thiagolunardi** [comment]
I found the issue's root cause.

If the certificate location doesn't exist on Windows, the `dotnet dev-certs` fail to write the certificate file.

I can create a pull request with a fix.
